import React, { useEffect } from 'react';
import { Link, useLocation } from 'react-router-dom';

export const Legal: React.FC = () => {
  const { pathname } = useLocation();
  const isPrivacy = pathname === '/privacy';

  useEffect(() => {
    window.scrollTo(0, 0);
  }, [pathname]);

  return (
    <div className="py-20 px-6">
      <div className="max-w-3xl mx-auto">
        <h1 className="text-3xl font-bold text-ops-text-main mb-8">
          {isPrivacy ? 'Privacy Policy' : 'Terms of Use'}
        </h1>
        
        <div className="space-y-8 text-sm leading-relaxed text-ops-text-muted bg-ops-panel/50 p-8 rounded-xl border border-ops-border">
          {isPrivacy ? (
            <>
              <section>
                <h2 className="text-lg font-bold text-ops-text-main mb-3">1. Data Collection</h2>
                <p>DebugOps collects information you provide directly to us, such as when you create an account, submit code snippets for analysis, or upload error logs. This includes technical data extracted from your uploaded files to perform debugging services.</p>
              </section>
              <section>
                <h2 className="text-lg font-bold text-ops-text-main mb-3">2. AI Processing</h2>
                <p>Our service utilizes Google Gemini API models to analyze your data. By using DebugOps, you acknowledge that your input data (code, logs) will be processed by third-party AI providers for the sole purpose of generating debugging insights.</p>
              </section>
              <section>
                <h2 className="text-lg font-bold text-ops-text-main mb-3">3. Data Security</h2>
                <p>We implement appropriate technical and organizational measures to protect the security of your personal information. However, please note that no method of transmission over the Internet is 100% secure.</p>
              </section>
            </>
          ) : (
            <>
              <section>
                <h2 className="text-lg font-bold text-ops-text-main mb-3">1. Acceptance of Terms</h2>
                <p>By accessing or using DebugOps, you agree to be bound by these Terms. If you disagree with any part of the terms, you may not access the service.</p>
              </section>
              <section>
                <h2 className="text-lg font-bold text-ops-text-main mb-3">2. Use License</h2>
                <p>DebugOps grants you a personal, non-transferable, non-exclusive license to use the software for your internal debugging and development purposes. You may not reverse engineer or attempt to extract the source code of the software.</p>
              </section>
              <section>
                <h2 className="text-lg font-bold text-ops-text-main mb-3">3. Disclaimer</h2>
                <p>The patches and analysis provided by DebugOps are generated by Artificial Intelligence. They are provided "as is" without warranty of any kind. You act on the agent's advice at your own risk. Always review code before deploying to production.</p>
              </section>
              <section>
                <h2 className="text-lg font-bold text-ops-text-main mb-3">4. Limitation of Liability</h2>
                <p>In no event shall DebugOps be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on DebugOps' website.</p>
              </section>
            </>
          )}
          
          <div className="pt-8 border-t border-ops-border mt-8">
            <p className="text-xs">Last Updated: October 2025</p>
            <p className="text-xs mt-2">Contact: legal@debugops.ai</p>
          </div>
        </div>
      </div>
    </div>
  );
};